version: '2.4'

services:
  squid:
    build:
      context: .
      dockerfile: Dockerfile-Squid
      args:
        SQUID_VERSION: "7.1"
        DISTRO: "jammy"
    container_name: squid_proxy
    ports:
      - "3128:3128"
    volumes:
      - ./squid_logs:/var/log/squid
      - ./squid_cache:/var/spool/squid
      - ./squid.conf:/etc/squid/squid.conf
    healthcheck:
      test: ["CMD", "/usr/lib/squid/squidclient", "-p", "3128", "mgr:info"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - squidnet
    restart: unless-stopped

  # squidstats:
  #   build: .
  #   container_name: squidstats_app
  #   ports:
  #     - "5001:5001"
  #   env_file:
  #     - .env
  #   environment:
  #     - FLASK_APP=app:app
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     squid:
  #       condition: service_healthy
  #   networks:
  #     - squidnet
  #   restart: unless-stopped

networks:
  squidnet:
    driver: bridge
